/* Resumen de la tabla HG WOLF FGB/FGB-K 24/28/35, edición ES 3066484_202209. */
window.WOLF_GUIDE = {
  parameters: [
    {code:'H01',name:'Histéresis de conexión del quemador',unit:'K',natural:'7',lpg:'7',min:'5',max:'30',group:'heating',tags:'histéresis arranque quemador',explain:'Diferencia de temperatura que gobierna la reconexión del quemador. Afecta a la frecuencia de los ciclos.',when:'Parámetro general de funcionamiento.',page:'34'},
    {code:'H02',name:'Potencia mínima del quemador / generador de calor',unit:'%',natural:'35',lpg:'33',min:'26',max:'100',group:'heating',tags:'potencia mínima modulación',explain:'Límite inferior de potencia del quemador. El fabricante indica que H02–H04 se modifican automáticamente cuando cambia H12.',when:'La fábrica da valores distintos según combustible para 24 kW.',page:'34–35'},
    {code:'H03',name:'Potencia máxima del quemador en ACS',unit:'%',natural:'100',lpg:'99',min:'26',max:'100',group:'dhw',tags:'ACS agua caliente potencia',explain:'Límite máximo de potencia del quemador durante la producción de agua caliente sanitaria. Ligado a la clase de gas/modelo.',when:'La fábrica da valores distintos según modelo y combustible; cambio automático al modificar H12.',page:'34–35'},
    {code:'H04',name:'Potencia máxima del quemador en calefacción',unit:'%',natural:'86',lpg:'84',min:'26',max:'100',group:'heating',tags:'calefacción potencia máxima',explain:'Límite máximo de potencia del quemador para calefacción. No confundir porcentaje de parámetro con kW de salida.',when:'La fábrica da valores distintos según modelo y combustible; cambio automático al modificar H12.',page:'34–35'},
    {code:'H07',name:'Retardo de la bomba del circuito de calefacción',unit:'min',natural:'2',lpg:'2',min:'0',max:'30',group:'heating',tags:'bomba retardo postcirculación',explain:'Tiempo que continúa funcionando la bomba del circuito de calefacción tras la demanda.',when:'Parámetro de calefacción.',page:'34'},
    {code:'H08',name:'Temperatura máxima de caldera en modo calefacción (TVmáx)',unit:'°C',natural:'75',lpg:'75',min:'40',max:'90',group:'heating',tags:'temperatura impulsión máxima límite caldera',explain:'Limita la temperatura máxima de la caldera durante calefacción. El manual utiliza H08 en ejemplos de curva climática.',when:'Parámetro de calefacción.',page:'34, 42–43'},
    {code:'H09',name:'Bloqueo de ciclo del quemador en calefacción',unit:'min',natural:'7',lpg:'7',min:'1',max:'30',group:'heating',tags:'bloqueo ciclos quemador anti ciclos',explain:'Tiempo de bloqueo entre ciclos de quemador durante calefacción.',when:'Parámetro de calefacción.',page:'34'},
    {code:'H10',name:'Dirección del generador de calor en eBus',unit:'—',natural:'1',lpg:'1',min:'1',max:'5',group:'service',tags:'eBus dirección',explain:'Dirección eBus asignada al generador de calor dentro del sistema.',when:'No cambiar sin comprobar el esquema de comunicación de la instalación.',page:'34'},
    {code:'H12',name:'Tipo de gas / clase de potencia',unit:'código',natural:'5',lpg:'6',min:'1',max:'6',group:'startup',tags:'tipo gas natural GLP propano conversión',explain:'Código según la tabla del fabricante: 1 = 28 kW natural; 2 = 28 kW GLP; 3 = 35 kW natural; 4 = 35 kW GLP; 5 = 24 kW natural; 6 = 24 kW GLP.',when:'Debe contrastarse en puesta en marcha y corresponde al combustible real. Para la selección 24 kW el manual requiere FW 4.30. La conversión física de gas y los ajustes son exclusivos del instalador autorizado.',page:'34–35, 45–46'},
    {code:'H15',name:'Histéresis del acumulador / diferencia de conmutación de carga',unit:'K',natural:'5',lpg:'5',min:'1',max:'30',group:'dhw',tags:'acumulador histéresis depósito',explain:'Diferencia de conmutación durante la carga del acumulador.',when:'Solo visible con H51 = 3 (modo acumulador); no es el modo normal ACS instantánea FGB-K.',page:'34'},
    {code:'H16',name:'Caudal mínimo de la bomba de calefacción',unit:'%',natural:'45',lpg:'45',min:'15',max:'100',group:'heating',tags:'bomba caudal mínimo',explain:'Porcentaje mínimo de caudal/velocidad de la bomba del circuito de calefacción.',when:'Valor de fábrica uniforme en la tabla.',page:'34'},
    {code:'H17',name:'Caudal máximo de la bomba de calefacción',unit:'%',natural:'95',lpg:'95',min:'15',max:'100',group:'heating',tags:'bomba caudal máximo',explain:'Porcentaje máximo de caudal/velocidad de la bomba del circuito de calefacción.',when:'Valor de fábrica uniforme en la tabla.',page:'34'},
    {code:'H19',name:'Retardo de la bomba en ACS',unit:'min',natural:'3',lpg:'3',min:'1',max:'10',group:'dhw',tags:'bomba ACS retardo acumulador',explain:'Tiempo de marcha posterior de la bomba asociado al funcionamiento de ACS.',when:'Solo visible con H51 = 1, 2 o 3.',page:'34'},
    {code:'H21',name:'Temperatura mínima de caldera en calefacción (TKmín)',unit:'°C',natural:'20',lpg:'20',min:'20',max:'90',group:'heating',tags:'temperatura mínima caldera calefacción',explain:'Límite inferior de temperatura de caldera en modo calefacción.',when:'Se usa junto a H08 y H54 para definir los extremos de la curva.',page:'34, 42–43'},
    {code:'H23',name:'Temperatura máxima de ACS',unit:'°C',natural:'65',lpg:'65',min:'60',max:'80',group:'dhw',tags:'agua caliente sanitaria temperatura máxima',explain:'Límite máximo de temperatura de ACS.',when:'Solo visible con H51 = 1, 2 o 3.',page:'35'},
    {code:'H25',name:'Sobretemperatura de caldera durante carga del acumulador',unit:'K',natural:'15',lpg:'15',min:'1',max:'30',group:'dhw',tags:'acumulador sobretemperatura',explain:'Margen de sobretemperatura de caldera usado durante la carga del acumulador.',when:'Solo visible con H51 = 3.',page:'35'},
    {code:'H34',name:'Selección de alimentación eBus',unit:'—',natural:'1',lpg:'1',min:'0',max:'1',group:'service',tags:'bus alimentación electrónica',explain:'Selecciona el modo de alimentación de la conexión eBus según el sistema instalado.',when:'Verificar compatibilidad del bus antes de cualquier cambio.',page:'35'},
    {code:'H37',name:'Tipo de regulación de la bomba',unit:'código',natural:'1',lpg:'1',min:'0',max:'1',group:'heating',tags:'bomba regulación salto térmico delta T',explain:'0 = valor fijo; 1 = regulación por salto térmico ΔT.',when:'La tabla del manual presenta 1 como valor de fábrica para la gama.',page:'35'},
    {code:'H38',name:'Consigna de salto térmico ΔT para regulación del caudal de bomba',unit:'°C',natural:'15',lpg:'15',min:'1',max:'30',group:'heating',tags:'delta T bomba caudal',explain:'Salto de temperatura usado por el control del caudal de la bomba de caldera.',when:'Relacionado con H37 cuando está activa la regulación por ΔT.',page:'35, 39'},
    {code:'H39',name:'Tiempo de arranque suave (Soft-Start)',unit:'min',natural:'3',lpg:'3',min:'0',max:'10',group:'heating',tags:'arranque suave',explain:'Duración del arranque suave del quemador.',when:'Valor de fábrica uniforme en la tabla.',page:'35, 39'},
    {code:'H40',name:'Configuración de la instalación',unit:'código',natural:'1',lpg:'1',min:'1',max:'60',group:'startup',tags:'instalación circuito calefacción módulo cascada configuración',explain:'1 = circuito de calefacción directo; 2 = módulo de mezcla sin circuito directo; 60 = módulo de cascada sin circuito directo.',when:'El fabricante pide comprobar H40 durante la puesta en marcha y adaptarlo a la instalación real.',page:'35, 39–40'},
    {code:'H41',name:'Velocidad de giro de la bomba de alimentación/circuito de calefacción',unit:'%',natural:'95',lpg:'95',min:'15',max:'100',group:'heating',tags:'bomba velocidad',explain:'Límite de velocidad de la bomba del circuito de alimentación/calefacción.',when:'Solo visible con H51 = 1, 2 o 3.',page:'35, 40'},
    {code:'H51',name:'Configuración de ACS',unit:'código',natural:'1 (FGB-K) / 4 (FGB)',lpg:'1 (FGB-K) / 4 (FGB)',min:'1',max:'4',group:'startup',tags:'configuración ACS agua caliente solar acumulador',explain:'1 = ACS mixta; 2 = ACS mixta + solar; 3 = modo acumulador; 4 = sin ACS (solo calefacción).',when:'Comprobar en puesta en marcha. FGB-K-24 es versión combinada; confirmar configuración de instalación. Con BM-2 algunas funciones se trasladan a esta unidad.',page:'35, 41'},
    {code:'H52',name:'Función de protección antilegionela',unit:'°C',natural:'5',lpg:'5',min:'0',max:'80',group:'dhw',tags:'legionela acumulador',explain:'Parámetro de la función de protección antilegionela del acumulador.',when:'Solo visible con H51 = 3. Con BM-2, esta función la ejecuta la BM-2.',page:'35, 41'},
    {code:'H53',name:'Intervalo de conexión de protección antilegionela',unit:'días',natural:'7',lpg:'7',min:'1',max:'7',group:'dhw',tags:'intervalo legionela días',explain:'Intervalo de activación de la función antilegionela.',when:'Solo visible con H51 = 3. Con BM-2, esta función la ejecuta la BM-2.',page:'35, 41'},
    {code:'H54',name:'Curva de calefacción',unit:'factor',natural:'0',lpg:'0',min:'0',max:'30',group:'heating',tags:'curva climática pendiente radiadores suelo radiante',explain:'Pendiente de la curva que adapta la temperatura de impulsión a la temperatura exterior. En un sistema bien aislado, el manual da como reglas orientativas 9 para radiadores y 3 para suelo radiante; el ajuste depende de edificio y clima.',when:'Con BM-2, se ajusta desde BM-2. La corrección de consigna de impulsión −4…+4 se calcula aparte: temperatura de curva + (H54 / 2,5 × corrección).',page:'35, 42–43'},
    {code:'H55',name:'Arranque rápido de ACS',unit:'modo',natural:'0',lpg:'0',min:'0 (Eco)',max:'1 (Confort)',group:'dhw',tags:'arranque rápido ACS eco confort',explain:'Selecciona el comportamiento de arranque rápido de agua caliente: 0 = Eco; 1 = Confort.',when:'Solo visible con H51 = 1 o 2. Con BM-2, la disponibilidad inmediata de ACS la gestiona la BM-2.',page:'35, 44'},
    {code:'A09',name:'Protección antihielo de la instalación',unit:'°C',natural:'2',lpg:'2',min:'−20',max:'10',group:'service',tags:'hielo congelación',explain:'Temperatura límite asociada a la protección antihielo de la instalación.',when:'Con BM-2, la protección antihielo la ejecuta la BM-2.',page:'35, 44'}
  ],
  startup: [
    {title:'1 · Preparación, identificación y responsabilidades',purpose:'Confirma que la unidad y la documentación corresponden al equipo y la instalación antes de iniciar la puesta en marcha.',items:['Registrar tipo exacto, número de serie, clase/categoría de gas y versión de firmware en la placa/datos del equipo.','Verificar que instalación, evacuación de gases y condensados están completas, permitidas y accesibles para su inspección.','Acordar qué controles realizará el alumnado como observación y cuáles ejecuta exclusivamente el instalador autorizado.'],evidence:'Modelo / número de serie / categoría de placa / firmware / responsable',detail:'El manual requiere que instalador y mantenedor lean las instrucciones antes de empezar. Las partes eléctricas y las que conducen gas se dejan a personal cualificado; para el control de gas se especifica instalador autorizado.',ref:'Manual, seguridad y alcance, capítulo 2; comprobación H12/H40/H51, p. 35.'},
    {title:'2 · Inspección, evacuación y estanqueidad hidráulica',purpose:'Descartar daños, fugas y problemas de conexión antes de llenar o energizar.',items:['Inspección visual de tuberías, uniones, desagüe de condensados, terminal de combustión y conexiones.','Realizar la comprobación de estanqueidad hidráulica con el equipo aislado según el escenario de prueba aplicable.','En la prueba de calefacción descrita en el capítulo 18, presión máxima de control 4 bar; cerrar las llaves hacia el equipo antes de probar. La válvula de seguridad puede abrir a 3 bar. El equipo fue probado en fábrica a 4,5 bar.'],evidence:'Resultado de estanqueidad / presión de prueba / unidad / quién valida',detail:'En el capítulo 12 el manual da también valores de comprobación de sistema: agua potable máx. 10 bar y calefacción máx. 4,5 bar. Para el procedimiento de puesta en marcha del capítulo 18, el texto señala máx. 4 bar en el circuito de calefacción. Respetar qué tramo se está probando y no superar el límite correspondiente.',ref:'Manual, capítulos 12 y 18; páginas impresas 21 y 45.'},
    {title:'3 · Acondicionamiento y llenado de calefacción',purpose:'Llenar y purgar lentamente el circuito, protegiendo la caldera y el agua potable.',items:['Limpiar el circuito antes de conectarlo para retirar residuos de soldadura, cáñamo, masilla, etc.','Con las llaves de gas cerradas, abrir válvulas del circuito; llenar lentamente por el dispositivo previsto.','Valor de llenado indicado: aproximadamente 1,2–1,6 bar; comprobar en pantalla y con manómetro externo si el procedimiento lo requiere.','Purgar radiadores/circuitos y volver a completar hasta presión de servicio. Comprobar la estanqueidad de conexiones.','No añadir anticongelantes ni inhibidores. En instalaciones mixtas el manual indica pH 8,2–9,0.'],evidence:'Presión final (bar) / pH / calidad del agua / observaciones',detail:'El manual recomienda acondicionamiento conforme a VDI 2035. Agua pobre en sales con conductividad <100 μS/cm minimiza corrosión; el tratamiento debe definirse para el volumen, dureza y materiales de la instalación.',ref:'Manual, capítulo 18, páginas impresas 45–48; cap. 19, p. 50.'},
    {title:'4 · Purgado y llenado del sifón de condensados',purpose:'Asegurar que la condensación puede evacuarse y evitar que gases de combustión salgan por el desagüe.',items:['Confirmar que el sifón está instalado con su junta en posición y el tubo de condensados con pendiente aproximada de 5°.','Llenar el sifón desde arriba a través del tubo de gases de combustión, antes de abrir la llave esférica de gas.','No verter agua por la toma de aire de combustión. La manguera de condensados no debe formar bucles ni contener burbujas.','Verificar evacuación libre y ausencia de fugas.'],evidence:'Sifón lleno / junta y desagüe verificados por',detail:'La instrucción de llenado advierte expresamente que verter agua por la abertura de aire puede dañar el quemador. El manual muestra el llenado a través del conducto de gases de combustión.',ref:'Manual, capítulos 12 y 18, páginas impresas 21 y 49.'},
    {title:'5 · Tipo de gas y presión de conexión',purpose:'Relacionar la placa del aparato, el suministro de gas y la configuración registrada antes de analizar la combustión.',items:['Confirmar el combustible real y la categoría marcada en la placa; comparar con las filas de España en la tabla de p. 52.','Presiones de conexión de gas natural en las filas ES: nominal 20 mbar, intervalo 18–25 mbar.','El manual presenta para GLP en España más de una categoría de placa: 37 mbar (25–45) o 50 mbar (42,5–57,5). La placa y la variante autorizada determinan cuál aplica.','Medición de presión con manómetro, registro en el acta y prueba de estanqueidad posterior: solo instalador autorizado. Si queda fuera de rango, el fabricante prohíbe ajuste o puesta en marcha.'],evidence:'Tipo/categoría de gas / presión medida / rango cotejado / técnico',detail:'El manual indica que el aparato sale ajustado para gas natural E/H. Para gas natural LL puede requerir retirar el obturador; para GLP P, sustituirlo. H12 usa códigos 5 (24 kW natural) y 6 (24 kW GLP); la selección de 24 kW requiere FW 4.30. Conversión, placa y comprobaciones son trabajo exclusivo del instalador autorizado.',ref:'Manual, capítulos 21–23, páginas impresas 52–55.'},
    {title:'6 · Encendido inicial y registro',purpose:'Arrancar solo cuando los controles anteriores están conformes y observar el ciclo de encendido.',items:['Confirmar que no hay fugas, el sifón está lleno, las llaves y conexiones están en el estado requerido y el equipo está cerrado.','El manual señala encendido con el botón de modalidades; cuando hay BM-2, esta función la ejecuta BM-2.','Observar indicación y funcionamiento; detener y escalar ante código de avería, olor a gas, ruido anómalo o fuga.','Registrar presión de conexión de gas en el acta tras el arranque.'],evidence:'Fecha/hora / estado mostrado / presión registrada / incidencias',detail:'La secuencia exacta de encendido se realiza conforme a la interfaz montada y la instalación. No puentear dispositivos de seguridad ni operar con el revestimiento abierto.',ref:'Manual, capítulo 22, p. 53; acta de puesta en marcha, cap. 27, p. 60–61.'},
    {title:'7 · Comprobación de CO₂ y análisis de combustión',purpose:'Verificar que el equipo quema correctamente a máxima y mínima carga, usando el combustible y estado de medición aplicables.',items:['Las mediciones de CO₂/O₂ las realiza un instalador con analizador calibrado y procedimiento del fabricante.','Con equipo abierto, valores del cuadro: carga máx. natural CO₂ 9,1±0,2 % / O₂ 4,5±0,3 %; GLP 10,2±0,2 % / 5,4±0,3 %. Carga mín. natural 8,9±0,2 % / 5,0±0,3 %; GLP 9,8±0,2 % / 6,0±0,3 %.','Análisis final con equipo cerrado: carga máx. natural 9,3±0,2 % / 4,2±0,3 %; GLP 10,5±0,2 % / 4,9±0,3 %. Carga mín. natural 9,1±0,2 % / 4,7±0,3 %; GLP 10,0±0,2 % / 5,7±0,3 %.','Medir también los parámetros requeridos del análisis y registrar instrumentos, condiciones y resultado. En la toma de aire, CO₂ >0,3 % indica fuga de evacuación que debe repararse.'],evidence:'Analizador / condición abierto-cerrado / CO₂ / O₂ / resultado',detail:'No mezclar las tablas: ajuste a equipo abierto y análisis final a equipo cerrado son condiciones distintas. Si un valor no cumple su tabla, el técnico resuelve y repite el análisis antes de aceptar la puesta en marcha. No usar estos valores para otro modelo/edición.',ref:'Manual, cap. 23, página impresa 55; cap. 25, p. 57.'},
    {title:'8 · Pruebas finales, acta y entrega',purpose:'Dejar trazabilidad de la instalación y entregar información segura al operador.',items:['Validar calefacción y ACS, evacuación de condensados, estanqueidad de gas y agua y ausencia de avisos.','Comprobar H12 (tipo de gas), H40 (configuración) y H51 (ACS) durante la puesta en marcha, adaptando únicamente si corresponde.','Completar el acta del fabricante con datos del equipo, gas, presiones, mediciones de combustión, temperaturas, fecha, responsable e incidencias.','Cerrar el equipo, reponer etiquetas de aviso tras conversión si aplica y explicar al operador la documentación y actuación ante una anomalía.'],evidence:'Acta completada / técnico responsable / operador informado',detail:'El manual reserva las modificaciones HG a instalador autorizado o servicio posventa WOLF. Los cambios de regulación se guardan inmediatamente; documentar el estado final y cualquier ajuste conforme al acta.',ref:'Manual, capítulos 16–17 y 27; páginas impresas 34–44 y 60–61.'}
  ]
};
